### ISSUE TITLE
"Error: Cannot find module 'app'" when capturing or displaying version

### ISSUE THREAD

**Issue by Calinou** [mixu/electroshot#7]
`electroshot google.com 1920x1080` fails with the following error on Windows 10:

```
module.js:338
    throw err;
    ^

Error: Cannot find module 'app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Hugo\AppData\Roaming\npm\node_modules\electroshot\electron\index.js:5:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
Electron exited with code 1
```

`electroshot -v` also returns an error after outputting the version:

```
shot v1.0.0
module.js:338
    throw err;
    ^

Error: Cannot find module 'app'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Hugo\AppData\Roaming\npm\node_modules\electroshot\electron\index.js:5:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

I used `npm install -g electroshot` to install Electroshot. Using Node.js 6.5.0.

**Comment by mixu** [comment]
thanks for reporting, finally fixed in `v1.2.0` which adds full Windows compatibility (and updates Electron to a 2017 release)
